//Generated by AI (lack of time)
using FluentAssertions;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata;
using Moq;
using PolicyManagement.Application.Contracts.Identity;
using PolicyManagement.Domain.Entities.DefaultDb.Identity;
using PolicyManagement.Infrastructure.Cache;
using PolicyManagementApp.Api.Controllers;
using System.Security.Claims;

namespace PolicyManagementApp.Api.UnitTests.Controllers;

public class AuthControllerTests
{
    private readonly Mock<IAuthService> _authServiceMock;
    private readonly Mock<ICacheHelper> _cacheHelperMock;
    private readonly AuthController _controller;
    
    public AuthControllerTests()
    {
        _authServiceMock = new Mock<IAuthService>();
        _cacheHelperMock = new Mock<ICacheHelper>();
        _controller = new AuthController(_authServiceMock.Object, _cacheHelperMock.Object);
        
        // Set up HttpContext for controller
        _controller.ControllerContext = new ControllerContext
        {
            HttpContext = new DefaultHttpContext()
        };
    }

    [Fact]
    public void CheckAuth_WhenError_ShouldReturnUnauthorized()
    {
        // Arrange - set up null User to force exception
        _controller.ControllerContext = new ControllerContext
        {
            HttpContext = new DefaultHttpContext { User = null }
        };

        // Act
        var actionResult = _controller.CheckAuth();

        // Assert
        var result = actionResult.Result.Should().BeOfType<UnauthorizedResult>().Subject;
        Assert.NotNull(result);
    }
} 