// Generated by AI
using System.IdentityModel.Tokens.Jwt;
using FluentAssertions;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Options;
using Moq;
using PolicyManagement.Domain.Entities.DefaultDb;
using PolicyManagement.Domain.Entities.DefaultDb.Identity;
using PolicyManagement.Domain.Entities.TenantsDb;
using PolicyManagement.Infrastructure.Cache;
using PolicyManagement.Infrastructure.DbContexts.TenantsDbContexts;
using PolicyManagement.Infrastructure.Repositories;
using PolicyManagement.Infrastructure.Services;
using Finbuckle.MultiTenant;
using Finbuckle.MultiTenant.Abstractions;

namespace PolicyManagement.Infrastructure.IntegrationTests;

public class JwtAndMultiTenantIntegrationTests
{
    private readonly JwtSettings _jwtSettings;
    private readonly AppTenantInfo _tenantInfo;
    private readonly Mock<IOptions<JwtSettings>> _jwtSettingsOptions;
    private readonly Mock<IMultiTenantContextAccessor> _multiTenantContextAccessor;
    private readonly Mock<IConfiguration> _configuration;
    private readonly Mock<ICacheHelper> _cacheHelper;
    
    public JwtAndMultiTenantIntegrationTests()
    {
        // JWT Settings
        _jwtSettings = new JwtSettings
        {
            Key = "YourSuperSecretKeyForTestingWithAtLeast32Characters",
            Issuer = "test-issuer",
            Audience = "test-audience",
            ExpiryMinutes = 60
        };

        _jwtSettingsOptions = new Mock<IOptions<JwtSettings>>();
        _jwtSettingsOptions.Setup(x => x.Value).Returns(_jwtSettings);
        
        // Tenant Info
        _tenantInfo = new AppTenantInfo
        {
            Id = "integration-tenant-1",
            Identifier = "integration-tenant",
            Name = "Integration Test Tenant",
            ConnectionString = "Data Source=:memory:;",
            DatabaseIdentifier = "IntegrationTestDb"
        };
        
        // Create multi-tenant context
        var multiTenantContext = new MultiTenantContext<AppTenantInfo>
        {
            TenantInfo = _tenantInfo
        };
        
        // Configure multi-tenant accessor mock
        _multiTenantContextAccessor = new Mock<IMultiTenantContextAccessor>();
        _multiTenantContextAccessor.Setup(m => m.MultiTenantContext).Returns(multiTenantContext);
        
        // Other mocks
        _configuration = new Mock<IConfiguration>();
        _cacheHelper = new Mock<ICacheHelper>();
    }
    
    [Fact]
    public void JwtToken_WithoutTenantId_ShouldHaveEmptyTenantId()
    {
        // Arrange
        var jwtTokenService = new JwtTokenService(_jwtSettingsOptions.Object);
        
        var userId = 2002;
        var user = new ApplicationUser
        {
            Id = userId,
            UserName = "non-tenant-user",
            Email = "notenant@example.com",
            TenantId = null // No tenant ID
        };
        
        var roles = new List<string> { "SystemUser" };
        
        // Act
        var token = jwtTokenService.GenerateToken(user, roles);
        
        // Assert
        var tokenHandler = new JwtSecurityTokenHandler();
        var jwtToken = tokenHandler.ReadJwtToken(token);
        
        var tenantIdClaim = jwtToken.Claims.FirstOrDefault(c => c.Type == "apptenid");
        tenantIdClaim.Should().NotBeNull();
        tenantIdClaim.Value.Should().Be(string.Empty);
    }
    
    [Fact]
    public async Task ChangingTenant_ShouldIsolateData()
    {
        // Arrange
        // Create first tenant
        var tenant1 = new AppTenantInfo
        {
            Id = "tenant1",
            Identifier = "first-tenant",
            Name = "First Tenant",
            ConnectionString = "Data Source=:memory:;",
            DatabaseIdentifier = "Tenant1Db"
        };
        
        // Create second tenant
        var tenant2 = new AppTenantInfo
        {
            Id = "tenant2",
            Identifier = "second-tenant",
            Name = "Second Tenant",
            ConnectionString = "Data Source=:memory:;",
            DatabaseIdentifier = "Tenant2Db"
        };
        
        // Create options for both tenants (using different DB names)
        var options1 = new DbContextOptionsBuilder<TenantDbContextBase>()
            .UseInMemoryDatabase(databaseName: $"TenantIsolation1_{Guid.NewGuid()}")
            .Options;
            
        var options2 = new DbContextOptionsBuilder<TenantDbContextBase>()
            .UseInMemoryDatabase(databaseName: $"TenantIsolation2_{Guid.NewGuid()}")
            .Options;
        
        // Create multi-tenant contexts for both tenants
        var multiTenantContext1 = new MultiTenantContext<AppTenantInfo> { TenantInfo = tenant1 };
        var multiTenantContext2 = new MultiTenantContext<AppTenantInfo> { TenantInfo = tenant2 };
        
        // Setup accessor mocks for both tenants
        var mockAccessor1 = new Mock<IMultiTenantContextAccessor>();
        mockAccessor1.Setup(m => m.MultiTenantContext).Returns(multiTenantContext1);
        
        var mockAccessor2 = new Mock<IMultiTenantContextAccessor>();
        mockAccessor2.Setup(m => m.MultiTenantContext).Returns(multiTenantContext2);
        
        // Act
        // Create policy in first tenant
        await using (var dbContext1 = new TenantDbContextBase(options1, mockAccessor1.Object, _configuration.Object))
        {
            var policyRepo1 = new PolicyRepository(dbContext1, _cacheHelper.Object);
            
            var policy1 = new Policy
            {
                Name = "Tenant 1 Policy",
                Description = "This policy belongs to tenant 1",
                CreationDate = DateTime.UtcNow,
                EffectiveDate = DateTime.UtcNow,
                ExpiryDate = DateTime.UtcNow.AddYears(1),
                IsActive = true,
                PolicyTypeId = 1
            };
            
            // Add policy directly without transaction
            await policyRepo1.AddAsync(policy1);
            await dbContext1.SaveChangesAsync();
        }
        
        // Create policy in second tenant
        await using (var dbContext2 = new TenantDbContextBase(options2, mockAccessor2.Object, _configuration.Object))
        {
            var policyRepo2 = new PolicyRepository(dbContext2, _cacheHelper.Object);
            
            var policy2 = new Policy
            {
                Name = "Tenant 2 Policy",
                Description = "This policy belongs to tenant 2",
                CreationDate = DateTime.UtcNow,
                EffectiveDate = DateTime.UtcNow,
                ExpiryDate = DateTime.UtcNow.AddYears(1),
                IsActive = true,
                PolicyTypeId = 1
            };
            
            // Add policy directly without transaction
            await policyRepo2.AddAsync(policy2);
            await dbContext2.SaveChangesAsync();
        }
        
        // Assert
        // Check tenant 1 context only has tenant 1 policy
        await using (var verifyContext1 = new TenantDbContextBase(options1, mockAccessor1.Object, _configuration.Object))
        {
            var tenant1Policy = await verifyContext1.Policies.FirstOrDefaultAsync(p => p.Name == "Tenant 1 Policy");
            var tenant2Policy = await verifyContext1.Policies.FirstOrDefaultAsync(p => p.Name == "Tenant 2 Policy");
            
            tenant1Policy.Should().NotBeNull();
            tenant2Policy.Should().BeNull();
        }
        
        // Check tenant 2 context only has tenant 2 policy
        await using (var verifyContext2 = new TenantDbContextBase(options2, mockAccessor2.Object, _configuration.Object))
        {
            var tenant1Policy = await verifyContext2.Policies.FirstOrDefaultAsync(p => p.Name == "Tenant 1 Policy");
            var tenant2Policy = await verifyContext2.Policies.FirstOrDefaultAsync(p => p.Name == "Tenant 2 Policy");
            
            tenant1Policy.Should().BeNull();
            tenant2Policy.Should().NotBeNull();
        }
    }
} 